from __future__ import annotations

import hashlib
import os
import subprocess
import tempfile
from collections.abc import Sequence
from dataclasses import dataclass
from importlib import resources
from pathlib import Path

from cinder.checker import SemanticModel, check
from cinder.codegen_c import generate_c, generate_module_header, generate_module_source
from cinder.ir import IRModule, lower
from cinder.lexer import lex
from cinder.lock_order import LockOrderGraph
from cinder.parser import parse
from cinder.project import ParsedModule, ProjectConfig, ProjectGraph
from cinder.symbols import ModuleSymbol
from cinder.toolchain import ToolchainResult, compile_c11, discover_compiler


@dataclass(frozen=True, slots=True)
class CompilerOptions:
    compiler: str | None = None
    c_flags: tuple[str, ...] = ()
    linker_flags: tuple[str, ...] = ()
    include_dirs: tuple[Path, ...] = ()
    debug: bool = False


@dataclass(frozen=True, slots=True)
class CompilationUnit:
    path: Path
    source: str
    semantic: SemanticModel
    ir: IRModule
    c_source: str
    module_name: str = ""
    header_name: str | None = None
    c_header: str | None = None
    generated_source_name: str | None = None


@dataclass(frozen=True, slots=True)
class CompilationProject:
    graph: ProjectGraph
    units: tuple[CompilationUnit, ...]

    @property
    def entry_unit(self) -> CompilationUnit:
        for unit in self.units:
            if unit.module_name == self.graph.entry_module:
                return unit
        raise AssertionError(f"entry module {self.graph.entry_module!r} was not compiled")

    @property
    def units_by_name(self) -> dict[str, CompilationUnit]:
        return {unit.module_name: unit for unit in self.units}

    @property
    def amalgamated_c(self) -> str:
        generated_headers = {
            unit.header_name
            for unit in self.units
            if unit.header_name is not None
        }
        sections = [
            "/* Generated by Cinder 0.5.0. */",
            f"/* Amalgamated project: {self.graph.config.name} */",
            "/* Compile as portable C11 together with cinder_runtime.c. */",
            "",
        ]
        for unit in self.units:
            if unit.c_header is not None:
                sections.append(
                    _remove_generated_header_includes(
                        unit.c_header, generated_headers
                    ).rstrip()
                )
                sections.append("")
        for unit in self.units:
            sections.append(
                _remove_generated_header_includes(
                    unit.c_source, generated_headers
                ).rstrip()
            )
            sections.append("")
        return "\n".join(sections).rstrip() + "\n"


@dataclass(frozen=True, slots=True)
class EmittedProject:
    project: CompilationProject
    sources: tuple[Path, ...]
    headers: tuple[Path, ...]


@dataclass(frozen=True, slots=True)
class BuildArtifact:
    unit: CompilationUnit
    executable: Path
    generated_c: Path
    toolchain: ToolchainResult
    project: CompilationProject
    generated_sources: tuple[Path, ...]
    generated_headers: tuple[Path, ...]


class Compiler:
    def __init__(self, options: CompilerOptions | None = None) -> None:
        self.options = options or CompilerOptions()

    def compile_source(
        self,
        source: str,
        path: Path | str = Path("<memory>.ci"),
    ) -> CompilationUnit:
        source_path = Path(path)
        tokens = lex(source, source_path)
        syntax = parse(tokens, source, source_path)
        lock_graph = LockOrderGraph()
        semantic = check(syntax, source, lock_graph=lock_graph)
        lock_graph.assign_canonical_keys()
        ir = lower(semantic)
        c_source = generate_c(ir)
        return CompilationUnit(
            path=source_path,
            source=source,
            semantic=semantic,
            ir=ir,
            c_source=c_source,
            module_name=source_path.stem,
        )

    def compile_project(self, path: Path | str) -> CompilationProject:
        graph = ProjectGraph.load(path)
        available_modules: dict[str, ModuleSymbol] = {}
        lock_graph = LockOrderGraph()
        checked_modules: list[tuple[ParsedModule, SemanticModel, str, str]] = []
        units: list[CompilationUnit] = []

        for parsed in graph.modules:
            header_name = _generated_header_name(parsed.name)
            generated_source_name = _generated_source_name(parsed.name)
            semantic = check(
                parsed.syntax,
                parsed.source,
                available_modules=available_modules,
                module_name=parsed.name,
                c_prefix=_module_c_prefix(graph.config.name, parsed.name),
                module_mode=True,
                is_entry=parsed.name == graph.entry_module,
                lock_graph=lock_graph,
            )
            module_symbol = semantic.module_symbol()
            module_symbol.generated_header = header_name
            available_modules[parsed.name] = module_symbol
            checked_modules.append((parsed, semantic, header_name, generated_source_name))

        lock_graph.assign_canonical_keys()

        for parsed, semantic, header_name, generated_source_name in checked_modules:
            ir = lower(semantic)
            dependency_headers = tuple(
                header
                for dependency in parsed.dependencies
                if (header := available_modules[dependency].generated_header) is not None
            )
            c_header = generate_module_header(ir, header_name, dependency_headers)
            c_source = generate_module_source(ir, header_name)
            unit = CompilationUnit(
                path=parsed.path,
                source=parsed.source,
                semantic=semantic,
                ir=ir,
                c_source=c_source,
                module_name=parsed.name,
                header_name=header_name,
                c_header=c_header,
                generated_source_name=generated_source_name,
            )
            units.append(unit)

        return CompilationProject(graph, tuple(units))

    def compile_file(self, path: Path | str) -> CompilationUnit:
        return self.compile_project(path).entry_unit

    def check_file(self, path: Path | str) -> SemanticModel:
        return self.compile_project(path).entry_unit.semantic

    def emit_c(self, path: Path | str) -> str:
        return self.compile_project(path).amalgamated_c

    def emit_project(
        self,
        path: Path | str,
        output_dir: Path | str,
    ) -> EmittedProject:
        project = self.compile_project(path)
        directory = Path(output_dir).expanduser().resolve()
        sources, headers = self._write_project(project, directory)
        return EmittedProject(project, sources, headers)

    def build(
        self,
        path: Path | str,
        *,
        output: Path | str | None = None,
        build_dir: Path | str | None = None,
    ) -> BuildArtifact:
        project = self.compile_project(path)
        config = project.graph.config
        output_path = self._output_path(config, output)
        working_directory = (
            Path(build_dir).expanduser().resolve()
            if build_dir is not None
            else config.root / ".cinder" / config.name
        )
        generated_sources, generated_headers = self._write_project(
            project,
            working_directory,
        )

        runtime_root = resources.files("cinder.runtime")
        runtime_c_resource = runtime_root.joinpath("cinder_runtime.c")
        with resources.as_file(runtime_c_resource) as runtime_c:
            runtime_include = runtime_c.parent
            compiler = discover_compiler(self.options.compiler)
            libraries = tuple(
                dict.fromkeys(
                    [
                        *(
                            library
                            for unit in project.units
                            for library in unit.semantic.libraries
                        ),
                        *config.libraries,
                    ]
                )
            )
            source_directories = tuple(
                dict.fromkeys(unit.path.parent for unit in project.units)
            )
            result = compile_c11(
                compiler=compiler,
                generated_c=generated_sources,
                runtime_c=runtime_c,
                runtime_include=runtime_include,
                output=output_path,
                libraries=libraries,
                c_flags=(*config.c_flags, *self.options.c_flags),
                linker_flags=(*config.linker_flags, *self.options.linker_flags),
                include_dirs=(
                    working_directory,
                    *project.graph.config.source_roots,
                    *source_directories,
                    *config.include_dirs,
                    *self.options.include_dirs,
                ),
                debug=self.options.debug,
                library_dirs=config.library_dirs,
                link_files=config.link_files,
            )

        entry_source = working_directory / project.entry_unit.generated_source_name
        return BuildArtifact(
            unit=project.entry_unit,
            executable=output_path,
            generated_c=entry_source,
            toolchain=result,
            project=project,
            generated_sources=generated_sources,
            generated_headers=generated_headers,
        )

    def run(
        self,
        path: Path | str,
        arguments: Sequence[str] = (),
    ) -> subprocess.CompletedProcess[str]:
        with tempfile.TemporaryDirectory(prefix="cinder-run-") as temporary:
            temp_path = Path(temporary)
            executable_name = "program.exe" if os.name == "nt" else "program"
            artifact = self.build(
                path,
                output=temp_path / executable_name,
                build_dir=temp_path / "build",
            )
            return subprocess.run(
                [str(artifact.executable), *arguments],
                check=False,
                text=True,
            )

    @staticmethod
    def _write_project(
        project: CompilationProject,
        directory: Path,
    ) -> tuple[tuple[Path, ...], tuple[Path, ...]]:
        sources: list[Path] = []
        headers: list[Path] = []
        for unit in project.units:
            assert unit.generated_source_name is not None
            assert unit.header_name is not None
            assert unit.c_header is not None
            source_path = directory / unit.generated_source_name
            header_path = directory / unit.header_name
            _write_if_changed(header_path, unit.c_header)
            _write_if_changed(source_path, unit.c_source)
            sources.append(source_path)
            headers.append(header_path)
        return tuple(sources), tuple(headers)

    @staticmethod
    def _output_path(config: ProjectConfig, output: Path | str | None) -> Path:
        if output is not None:
            return Path(output).expanduser().resolve()
        suffix = ".exe" if os.name == "nt" else ""
        return config.root / f"{config.name}{suffix}"


def _module_c_prefix(project_name: str, module_name: str) -> str:
    qualified_name = f"{project_name}.{module_name}"
    readable = "_".join(part for part in qualified_name.split(".") if part)
    readable = "".join(
        character
        if character.isascii() and (character.isalnum() or character == "_")
        else "_"
        for character in readable
    )
    digest = hashlib.sha256(qualified_name.encode("utf-8")).hexdigest()[:8]
    return f"cinder_{readable}_{digest}__"


def _generated_header_name(module_name: str) -> str:
    path = Path("cinder_gen", *module_name.split("."))
    return path.with_suffix(".cinder.h").as_posix()


def _generated_source_name(module_name: str) -> str:
    path = Path("cinder_gen", *module_name.split("."))
    return path.with_suffix(".c").as_posix()


def _write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        current = path.read_text(encoding="utf-8")
    except FileNotFoundError:
        current = None
    if current == content:
        return
    temporary = path.with_name(f".{path.name}.tmp")
    temporary.write_text(content, encoding="utf-8", newline="\n")
    temporary.replace(path)


def _remove_generated_header_includes(
    source: str,
    generated_headers: set[str],
) -> str:
    include_lines = {
        f'#include "{header}"'
        for header in generated_headers
        if header is not None
    }
    return "\n".join(
        line for line in source.splitlines() if line not in include_lines
    )
