/* Generated by Cinder 0.5.0. */
/* Amalgamated project: a1_aggregate_cast */
/* Compile as portable C11 together with cinder_runtime.c. */

/* Generated by Cinder 0.5.0. */
/* Public declarations for a1_aggregate_cast. */
/* This header is portable C11. */

#ifndef CINDER_GEN_A1_AGGREGATE_CAST_CINDER_H_INCLUDED
#define CINDER_GEN_A1_AGGREGATE_CAST_CINDER_H_INCLUDED

#include "cinder_runtime.h"
#include <stdlib.h>
#include <string.h>

typedef struct cinder_a1_aggregate_cast_a1_aggregate_cast_06a61ed7__A cinder_a1_aggregate_cast_a1_aggregate_cast_06a61ed7__A;
typedef struct cinder_a1_aggregate_cast_a1_aggregate_cast_06a61ed7__B cinder_a1_aggregate_cast_a1_aggregate_cast_06a61ed7__B;

struct cinder_a1_aggregate_cast_a1_aggregate_cast_06a61ed7__A
{
    int32_t x;
};

struct cinder_a1_aggregate_cast_a1_aggregate_cast_06a61ed7__B
{
    int32_t y;
};

#ifdef __cplusplus
extern "C" {
#endif

int main(void);

#ifdef __cplusplus
}
#endif

#endif /* CINDER_GEN_A1_AGGREGATE_CAST_CINDER_H_INCLUDED */

/* Generated by Cinder 0.5.0. */
/* Source: /Volumes/Shelfy/Code/Cinder/.scratch/repros/a1_aggregate_cast.ci */
/* This translation unit is portable C11. */


int main(void)
{
    cinder_a1_aggregate_cast_a1_aggregate_cast_06a61ed7__A a = { .x = 1 };
    cinder_a1_aggregate_cast_a1_aggregate_cast_06a61ed7__B b;
    /* unsafe */
    {
        b = ((cinder_a1_aggregate_cast_a1_aggregate_cast_06a61ed7__B)(a));
    }
    return (b).y;
}
