/* Generated by Cinder 0.5.0. */
/* Amalgamated project: a2_list_collision */
/* Compile as portable C11 together with cinder_runtime.c. */

/* Generated by Cinder 0.5.0. */
/* Public declarations for a2_list_collision. */
/* This header is portable C11. */

#ifndef CINDER_GEN_A2_LIST_COLLISION_CINDER_H_INCLUDED
#define CINDER_GEN_A2_LIST_COLLISION_CINDER_H_INCLUDED

#include "cinder_runtime.h"
#include <stdlib.h>
#include <string.h>

typedef struct cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32;
#ifndef CINDER_DECLARED_CINDERLIST_CINDER_A2_LIST_COLLISION_A2_LIST_COLLISION_B29392F6__PTR_I32
#define CINDER_DECLARED_CINDERLIST_CINDER_A2_LIST_COLLISION_A2_LIST_COLLISION_B29392F6__PTR_I32
typedef struct CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32;
#endif
#ifndef CINDER_DECLARED_CINDERLIST_PTR_I32
#define CINDER_DECLARED_CINDERLIST_PTR_I32
typedef struct CinderList_ptr_i32 CinderList_ptr_i32;
#endif

#ifndef CINDER_DEFINED_CINDERLIST_CINDER_A2_LIST_COLLISION_A2_LIST_COLLISION_B29392F6__PTR_I32
#define CINDER_DEFINED_CINDERLIST_CINDER_A2_LIST_COLLISION_A2_LIST_COLLISION_B29392F6__PTR_I32
struct CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32
{
    cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 *data;
    size_t length;
    size_t capacity;
};
#endif /* CINDER_DEFINED_CINDERLIST_CINDER_A2_LIST_COLLISION_A2_LIST_COLLISION_B29392F6__PTR_I32 */

#ifndef CINDER_DEFINED_CINDERLIST_PTR_I32
#define CINDER_DEFINED_CINDERLIST_PTR_I32
struct CinderList_ptr_i32
{
    int32_t **data;
    size_t length;
    size_t capacity;
};
#endif /* CINDER_DEFINED_CINDERLIST_PTR_I32 */

struct cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32
{
    int32_t x;
};

#ifdef __cplusplus
extern "C" {
#endif

static inline CINDER_MAYBE_UNUSED void CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32_drop(CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 *value);
static inline CINDER_MAYBE_UNUSED void CinderList_ptr_i32_drop(CinderList_ptr_i32 *value);

#ifndef CINDER_HELPERS_CINDERLIST_CINDER_A2_LIST_COLLISION_A2_LIST_COLLISION_B29392F6__PTR_I32
#define CINDER_HELPERS_CINDERLIST_CINDER_A2_LIST_COLLISION_A2_LIST_COLLISION_B29392F6__PTR_I32
static inline CINDER_MAYBE_UNUSED CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32_from_values(const cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 *values, size_t length)
{
    CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 result = { NULL, 0, 0 };
    if (length == 0)
    {
        return result;
    }
    result.data = (cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 *)cinder_alloc(length, sizeof(cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32));
    memcpy(result.data, values, length * sizeof(*result.data));
    result.length = length;
    result.capacity = length;
    return result;
}

static inline CINDER_MAYBE_UNUSED void CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32_drop(CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 *value)
{
    if (value == NULL)
    {
        return;
    }
    free(value->data);
    value->data = NULL;
    value->length = 0;
    value->capacity = 0;
}

static inline CINDER_MAYBE_UNUSED void CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32_append(CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 *value, cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 item)
{
    if (value->length == SIZE_MAX)
    {
        cinder_panic("List length overflow");
    }
    value->data = (cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 *)cinder_grow_array(
        value->data,
        &value->capacity,
        value->length + 1,
        sizeof(*value->data)
    );
    value->data[value->length] = item;
    value->length += 1;
}

static inline CINDER_MAYBE_UNUSED cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32_pop(CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 *value)
{
    if (value->length == 0)
    {
        cinder_panic("pop from empty List");
    }
    value->length -= 1;
    cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 result = value->data[value->length];
    return result;
}

static inline CINDER_MAYBE_UNUSED void CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32_clear(CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 *value)
{
    if (value == NULL)
    {
        return;
    }
    value->length = 0;
}
#endif /* CINDER_HELPERS_CINDERLIST_CINDER_A2_LIST_COLLISION_A2_LIST_COLLISION_B29392F6__PTR_I32 */

#ifndef CINDER_HELPERS_CINDERLIST_PTR_I32
#define CINDER_HELPERS_CINDERLIST_PTR_I32
static inline CINDER_MAYBE_UNUSED CinderList_ptr_i32 CinderList_ptr_i32_from_values(int32_t * const *values, size_t length)
{
    CinderList_ptr_i32 result = { NULL, 0, 0 };
    if (length == 0)
    {
        return result;
    }
    result.data = (int32_t **)cinder_alloc(length, sizeof(int32_t *));
    memcpy(result.data, values, length * sizeof(*result.data));
    result.length = length;
    result.capacity = length;
    return result;
}

static inline CINDER_MAYBE_UNUSED void CinderList_ptr_i32_drop(CinderList_ptr_i32 *value)
{
    if (value == NULL)
    {
        return;
    }
    free(value->data);
    value->data = NULL;
    value->length = 0;
    value->capacity = 0;
}

static inline CINDER_MAYBE_UNUSED void CinderList_ptr_i32_append(CinderList_ptr_i32 *value, int32_t *item)
{
    if (value->length == SIZE_MAX)
    {
        cinder_panic("List length overflow");
    }
    value->data = (int32_t **)cinder_grow_array(
        value->data,
        &value->capacity,
        value->length + 1,
        sizeof(*value->data)
    );
    value->data[value->length] = item;
    value->length += 1;
}

static inline CINDER_MAYBE_UNUSED int32_t *CinderList_ptr_i32_pop(CinderList_ptr_i32 *value)
{
    if (value->length == 0)
    {
        cinder_panic("pop from empty List");
    }
    value->length -= 1;
    int32_t *result = value->data[value->length];
    return result;
}

static inline CINDER_MAYBE_UNUSED void CinderList_ptr_i32_clear(CinderList_ptr_i32 *value)
{
    if (value == NULL)
    {
        return;
    }
    value->length = 0;
}
#endif /* CINDER_HELPERS_CINDERLIST_PTR_I32 */

int main(void);

#ifdef __cplusplus
}
#endif

#endif /* CINDER_GEN_A2_LIST_COLLISION_CINDER_H_INCLUDED */

/* Generated by Cinder 0.5.0. */
/* Source: /Volumes/Shelfy/Code/Cinder/.scratch/repros/a2_list_collision.ci */
/* This translation unit is portable C11. */


int main(void)
{
    CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 a = CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32_from_values((cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32 [1]){ ((cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32){ .x = 1 }) }, 1);
    int32_t *p = ((int32_t *)cinder_alloc(1, sizeof(int32_t)));
    (*p) = 2;
    CinderList_ptr_i32 b = CinderList_ptr_i32_from_values((int32_t *[1]){ p }, 1);
    int32_t __cinder_return_1 = (((a).data[0]).x + (*(b).data[0]));
    CinderList_ptr_i32_drop(&b);
    CinderList_cinder_a2_list_collision_a2_list_collision_b29392f6__ptr_i32_drop(&a);
    return __cinder_return_1;
}
