/* Generated by Cinder 0.5.0. */
/* Source: collision.ci */
/* This file is portable C11 and may be read or compiled directly. */

#include "cinder_runtime.h"
#include <stdlib.h>
#include <string.h>

typedef struct ptr_i32 ptr_i32;

struct ptr_i32
{
    int32_t x;
};

int main(void);
static CINDER_MAYBE_UNUSED int32_t *id_ptr_i32(int32_t *value);

int main(void)
{
    ptr_i32 s = { .x = 10 };
    int32_t *p = ((int32_t *)cinder_alloc(1, sizeof(int32_t)));
    (*p) = 20;
    ptr_i32 a = id_ptr_i32(s);
    int32_t *b = id_ptr_i32(p);
    return ((a).x + (*b));
}

static CINDER_MAYBE_UNUSED int32_t *id_ptr_i32(int32_t *value)
{
    (void)value;
    return value;
}
