/* Generated by Cinder 0.5.0. */
/* Amalgamated project: a2_typekey_collision */
/* Compile as portable C11 together with cinder_runtime.c. */

/* Generated by Cinder 0.5.0. */
/* Public declarations for a2_typekey_collision. */
/* This header is portable C11. */

#ifndef CINDER_GEN_A2_TYPEKEY_COLLISION_CINDER_H_INCLUDED
#define CINDER_GEN_A2_TYPEKEY_COLLISION_CINDER_H_INCLUDED

#include "cinder_runtime.h"
#include <stdlib.h>
#include <string.h>

typedef struct cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32 cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32;

struct cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32
{
    int32_t x;
};

#ifdef __cplusplus
extern "C" {
#endif

int main(void);
static CINDER_MAYBE_UNUSED cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32 cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__id_cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32(cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32 value);
static CINDER_MAYBE_UNUSED int32_t *cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__id_ptr_i32(int32_t *value);

#ifdef __cplusplus
}
#endif

#endif /* CINDER_GEN_A2_TYPEKEY_COLLISION_CINDER_H_INCLUDED */

/* Generated by Cinder 0.5.0. */
/* Source: /Volumes/Shelfy/Code/Cinder/.scratch/repros/a2_typekey_collision.ci */
/* This translation unit is portable C11. */


int main(void)
{
    cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32 s = { .x = 10 };
    int32_t *p = ((int32_t *)cinder_alloc(1, sizeof(int32_t)));
    (*p) = 20;
    cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32 a = cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__id_cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32(s);
    int32_t *b = cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__id_ptr_i32(p);
    return ((a).x + (*b));
}

static CINDER_MAYBE_UNUSED cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32 cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__id_cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32(cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__ptr_i32 value)
{
    (void)value;
    return value;
}

static CINDER_MAYBE_UNUSED int32_t *cinder_a2_typekey_collision_a2_typekey_collision_61d3744c__id_ptr_i32(int32_t *value)
{
    (void)value;
    return value;
}
