/* Generated by Cinder 0.5.0. */
/* Amalgamated project: b1_match_list */
/* Compile as portable C11 together with cinder_runtime.c. */

/* Generated by Cinder 0.5.0. */
/* Public declarations for b1_match_list. */
/* This header is portable C11. */

#ifndef CINDER_GEN_B1_MATCH_LIST_CINDER_H_INCLUDED
#define CINDER_GEN_B1_MATCH_LIST_CINDER_H_INCLUDED

#include "cinder_runtime.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

#ifndef CINDER_DECLARED_CINDERLIST_I32
#define CINDER_DECLARED_CINDERLIST_I32
typedef struct CinderList_i32 CinderList_i32;
#endif
#ifndef CINDER_DECLARED_CINDEROPTION_LIST_I32
#define CINDER_DECLARED_CINDEROPTION_LIST_I32
typedef struct CinderOption_list_i32 CinderOption_list_i32;
#endif

#ifndef CINDER_DEFINED_CINDERLIST_I32
#define CINDER_DEFINED_CINDERLIST_I32
struct CinderList_i32
{
    int32_t *data;
    size_t length;
    size_t capacity;
};
#endif /* CINDER_DEFINED_CINDERLIST_I32 */

#ifndef CINDER_DEFINED_CINDEROPTION_LIST_I32
#define CINDER_DEFINED_CINDEROPTION_LIST_I32
typedef enum CinderOption_list_i32_Tag
{
    CinderOption_list_i32_Tag_None = 0,
    CinderOption_list_i32_Tag_Some = 1
} CinderOption_list_i32_Tag;

struct CinderOption_list_i32
{
    CinderOption_list_i32_Tag tag;
    union
    {
        unsigned char _cinder_empty;
        CinderList_i32 value;
    } data;
};

static inline CINDER_MAYBE_UNUSED CinderList_i32 CinderOption_list_i32_value_or_panic(const CinderOption_list_i32 *option)
{
    if (option == NULL || option->tag != CinderOption_list_i32_Tag_Some)
    {
        cinder_panic("attempted to read None.value");
    }
    return option->data.value;
}
#endif /* CINDER_DEFINED_CINDEROPTION_LIST_I32 */

#ifdef __cplusplus
extern "C" {
#endif

static inline CINDER_MAYBE_UNUSED void CinderList_i32_drop(CinderList_i32 *value);
static inline CINDER_MAYBE_UNUSED void CinderOption_list_i32_drop(CinderOption_list_i32 *value);

static inline CINDER_MAYBE_UNUSED void CinderOption_list_i32_drop(CinderOption_list_i32 *value)
{
    if (value == NULL)
    {
        return;
    }
    if (value->tag == CinderOption_list_i32_Tag_Some)
    {
        CinderList_i32_drop(&(value->data.value));
    }
}

#ifndef CINDER_HELPERS_CINDERLIST_I32
#define CINDER_HELPERS_CINDERLIST_I32
static inline CINDER_MAYBE_UNUSED CinderList_i32 CinderList_i32_from_values(const int32_t *values, size_t length)
{
    CinderList_i32 result = { NULL, 0, 0 };
    if (length == 0)
    {
        return result;
    }
    result.data = (int32_t *)cinder_alloc(length, sizeof(int32_t));
    memcpy(result.data, values, length * sizeof(*result.data));
    result.length = length;
    result.capacity = length;
    return result;
}

static inline CINDER_MAYBE_UNUSED void CinderList_i32_drop(CinderList_i32 *value)
{
    if (value == NULL)
    {
        return;
    }
    free(value->data);
    value->data = NULL;
    value->length = 0;
    value->capacity = 0;
}

static inline CINDER_MAYBE_UNUSED void CinderList_i32_append(CinderList_i32 *value, int32_t item)
{
    if (value->length == SIZE_MAX)
    {
        cinder_panic("List length overflow");
    }
    value->data = (int32_t *)cinder_grow_array(
        value->data,
        &value->capacity,
        value->length + 1,
        sizeof(*value->data)
    );
    value->data[value->length] = item;
    value->length += 1;
}

static inline CINDER_MAYBE_UNUSED int32_t CinderList_i32_pop(CinderList_i32 *value)
{
    if (value->length == 0)
    {
        cinder_panic("pop from empty List");
    }
    value->length -= 1;
    int32_t result = value->data[value->length];
    return result;
}

static inline CINDER_MAYBE_UNUSED void CinderList_i32_clear(CinderList_i32 *value)
{
    if (value == NULL)
    {
        return;
    }
    value->length = 0;
}
#endif /* CINDER_HELPERS_CINDERLIST_I32 */

#include <stdio.h>

static inline CINDER_MAYBE_UNUSED void CinderList_i32_print(const CinderList_i32 *value);

#ifndef CINDER_PRINT_CINDERLIST_I32
#define CINDER_PRINT_CINDERLIST_I32
static inline CINDER_MAYBE_UNUSED void CinderList_i32_print(const CinderList_i32 *value)
{
    printf("[");
    for (size_t index = 0; index < value->length; ++index)
    {
        if (index) printf(", ");
        printf("%lld", (long long)(value->data[index]));
    }
    printf("]");
}
#endif /* CINDER_PRINT_CINDERLIST_I32 */

CinderList_i32 cinder_b1_match_list_b1_match_list_0f883c47__take(void);
int main(void);

#ifdef __cplusplus
}
#endif

#endif /* CINDER_GEN_B1_MATCH_LIST_CINDER_H_INCLUDED */

/* Generated by Cinder 0.5.0. */
/* Source: /Volumes/Shelfy/Code/Cinder/.scratch/repros/b1_match_list.ci */
/* This translation unit is portable C11. */


CinderList_i32 cinder_b1_match_list_b1_match_list_0f883c47__take(void)
{
    CinderOption_list_i32 o = { .tag = CinderOption_list_i32_Tag_Some, .data.value = CinderList_i32_from_values((int32_t [3]){ 1, 2, 3 }, 3) };
    {
        CinderOption_list_i32 __cinder_match_1 = o;
        if (__cinder_match_1.tag == CinderOption_list_i32_Tag_Some)
        {
            const CinderList_i32 v = __cinder_match_1.data.value;
            CinderList_i32 __cinder_return_2 = v;
            CinderOption_list_i32_drop(&o);
            return __cinder_return_2;
        }
        else if (__cinder_match_1.tag == CinderOption_list_i32_Tag_None)
        {
            CinderList_i32 __cinder_return_3 = CinderList_i32_from_values(NULL, 0);
            CinderOption_list_i32_drop(&o);
            return __cinder_return_3;
        }
        else
        {
            cinder_panic("invalid tag in exhaustive match");
        }
    }
}

int main(void)
{
    CinderList_i32 xs = cinder_b1_match_list_b1_match_list_0f883c47__take();
    printf("%llu %lld\n", ((unsigned long long)((xs).length)), ((long long)((xs).data[0])));
    int32_t __cinder_return_4 = 0;
    CinderList_i32_drop(&xs);
    return __cinder_return_4;
}
